import { NextResponse } from "next/server";
import { approveLessonRequest, getLessonRequests, readPlatform, rejectLessonRequest } from "@/lib/server/data-store";
import { generateRefresherLesson } from "@/lib/incidents/generate-lesson";
import type { Lesson } from "@/lib/types";

export async function GET() {
  const data = await readPlatform();
  return NextResponse.json({ requests: data.lessonRequests || [] });
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { action, requestId, orgId } = body as { action: string; requestId: string; orgId?: string };

    if (action === 'approve') {
      const data = await readPlatform();
      const req = (data.lessonRequests || []).find((r) => r.id === requestId);
      if (!req) return NextResponse.json({ error: "Request not found" }, { status: 404 });

      // Generate or use suggested lesson
      let lesson: Lesson;
      if (req.suggestedLesson && req.suggestedLesson.title) {
        lesson = {
          id: `lesson-approved-${Date.now()}`,
          orgId: req.orgId,
          title: req.suggestedLesson.title,
          description: req.suggestedLesson.description || req.description,
          category: req.suggestedLesson.category || "Compliance",
          estimatedMinutes: req.suggestedLesson.estimatedMinutes || 2,
          slides: (req.suggestedLesson.slides || [{ title: "Key Points", body: req.description }]).map((s: any, i: number) => ({ id: `s${i}`, title: s.title || "Point", body: s.body || s, durationSeconds: 60 })),
          quiz: req.suggestedLesson.quiz || [{
            id: "q1",
            prompt: `What is the main takeaway from the incident or pain point: ${req.title}?`,
            options: ["Follow the procedure exactly", "Ignore it", "Ask later", "Document only"],
            correctIndex: 0,
            explanation: "Follow documented procedures to prevent recurrence.",
          }],
          sourceDocumentIds: [],
          isAutoGenerated: true,
          generatedFromIncidentId: undefined,
        } as Lesson;
      } else {
        // Fallback generate a simple one
        lesson = {
          id: `lesson-approved-${Date.now()}`,
          orgId: req.orgId,
          title: req.title,
          description: req.description,
          category: "Compliance",
          estimatedMinutes: 2,
          slides: [{ id: "s1", title: "Review", body: req.description, durationSeconds: 60 }],
          quiz: [{ id: "q1", prompt: "Key action?", options: ["Yes", "No", "Maybe", "Later"], correctIndex: 0, explanation: "Follow the guidance." }],
          sourceDocumentIds: [],
          isAutoGenerated: true,
        } as Lesson;
      }

      // For demo, assign to all current staff of org
      const staff = data.users.filter((u) => u.orgId === req.orgId && u.role === "staff").map((u) => u.id);
      const result = await approveLessonRequest(requestId, lesson, staff);

      return NextResponse.json({ ok: true, request: result.request, lesson: result.lesson });
    }

    if (action === 'reject') {
      const result = await rejectLessonRequest(requestId);
      return NextResponse.json({ ok: true, request: result });
    }

    return NextResponse.json({ error: "Unknown action" }, { status: 400 });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || "Action failed" }, { status: 500 });
  }
}
