export type UserRole = "staff" | "manager";

export type OrgType = "snf" | "behavioral_health" | "home_health";

export type TutorCardType = "teach" | "quiz" | "progress" | "gap_review";

export type IncidentSeverity = "low" | "medium" | "high";

export type LessonStatus = "not_started" | "in_progress" | "completed";

export type UploadFileType = "pdf" | "docx" | "pptx" | "image" | "text" | "unknown";

export type UploadStatus =
  | "uploaded"
  | "processing"
  | "ready"
  | "error"
  | "submitted_by_manager";

export interface Organization {
  id: string;
  name: string;
  industry: string;
  orgType?: OrgType;
  /** When false, staff skip timed rotation — lessons only, no auto refreshers. Default: on. */
  refresherRotationEnabled?: boolean;
}

export interface Team {
  id: string;
  orgId: string;
  name: string;
}

export interface User {
  id: string;
  orgId: string;
  teamId: string;
  name: string;
  email: string;
  role: UserRole;
  avatarInitials: string;
  jobTitle?: string;
  priorityCategories?: string[];  // Manager-set priorities for this staff's assignments (subset of org's categories)
  refresherIntervalDays?: number; // Default days between refreshers (manager-controlled)
  refresherIntervals?: Record<string, number>; // Per-category override for refresher cycle
  refresherCycleStartedAt?: string; // Anchor for staggered one-at-a-time refresher rotation
}

export interface UploadedMaterial {
  id: string;
  orgId: string;
  fileName: string;
  fileType: UploadFileType;
  mimeType: string;
  fileSize: number;
  storagePath: string;
  status: UploadStatus;
  uploadedAt: string;
  processedAt?: string;
  extractedText?: string;
  lessonIds: string[];
  errorMessage?: string;
  assignedCategories?: string[];  // Admin-confirmed categories (can be multiple) after AI suggestion on upload
  // For manager-submitted lesson requests (note + file info for admin to process via regular upload + AI)
  managerRequestNote?: string;
  managerId?: string;
  managerName?: string;
}

export interface DocumentChunk {
  id: string;
  orgId: string;
  documentId: string;
  documentTitle: string;
  section: string;
  content: string;
  keywords: string[];
  competencyDomainId?: string;
}

export interface QuizQuestion {
  id: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface LessonSlide {
  id: string;
  title: string;
  body: string;
  durationSeconds: number;
}

export interface Lesson {
  id: string;
  orgId: string;
  title: string;
  description: string;
  category: string;
  estimatedMinutes: number;
  slides: LessonSlide[];
  quiz: QuizQuestion[];
  sourceDocumentIds: string[];
  isRefresher?: boolean;
  generatedFromIncidentId?: string;
  isAutoGenerated?: boolean;
  xpReward?: number;
  orderIndex?: number;
  competencyDomainId?: string;
}

export interface CompetencyDomain {
  id: string;
  orgId: string;
  name: string;
  slug: string;
  description?: string;
  sourceDocumentIds: string[];
  refresherIntervalDays?: number; // Org-wide default interval for this category (manager-controlled)
}

export interface CompetencyRecord {
  userId: string;
  domainId: string;
  masteryPercent: number;
  assessmentCount: number;
  correctCount: number;
  lastAssessedAt?: string;
  gapNotes?: string;
}

export interface AssessmentEvent {
  id: string;
  userId: string;
  orgId: string;
  domainId: string;
  sessionId: string;
  question: string;
  selectedIndex: number;
  correctIndex: number;
  correct: boolean;
  sourceDocumentId?: string;
  lessonId?: string;
  createdAt: string;
}

export interface LearningSession {
  id: string;
  userId: string;
  orgId: string;
  startedAt: string;
  lastActiveAt: string;
  topicsCovered: string[];
  assessmentCount: number;
}

export interface TutorCard {
  id: string;
  type: TutorCardType;
  title?: string;
  body?: string;
  hook?: string;
  slides?: Array<{ title: string; body: string }>;
  question?: string;
  options?: string[];
  correctIndex?: number;
  domainId?: string;
  domainName?: string;
  lessonId?: string;
  citation?: {
    documentTitle: string;
    section: string;
  };
  masteryBefore?: number;
  masteryAfter?: number;
  xpEarned?: number;
  answered?: boolean;
  selectedIndex?: number;
  wasCorrect?: boolean;
  explanation?: string;
}

export interface TutorMessage {
  id: string;
  sessionId: string;
  userId: string;
  role: "user" | "assistant";
  content: string;
  cards?: TutorCard[];
  createdAt: string;
}

export interface DomainAssignment {
  id: string;
  orgId: string;
  domainId: string;
  userId: string;
  assignedBy: string;
  assignedAt: string;
}

export interface LessonAssignment {
  id: string;
  lessonId: string;
  userId: string;
  assignedAt: string;
  dueAt?: string;
}

export interface LessonProgress {
  userId: string;
  lessonId: string;
  status: LessonStatus;
  currentSlideIndex: number;
  quizScore?: number;
  completedAt?: string;
  lastAccessedAt: string;
  xpEarned?: number;
}

export interface UserXP {
  userId: string;
  totalXp: number;
  level: number;
  dailyXp: number;
  dailyGoal: number;
  lastXpDate: string;
}

export interface Streak {
  userId: string;
  currentStreak: number;
  longestStreak: number;
  lastActivityDate: string;
}

export interface Incident {
  id: string;
  orgId: string;
  teamId: string;
  reportedBy: string;
  title: string;
  description: string;
  severity: IncidentSeverity;
  category: string;
  occurredAt: string;
  suggestedLessonId?: string;
  status: "open" | "lesson_assigned" | "resolved";
}

export interface LessonRequest {
  id: string;
  orgId: string;
  requestedBy: string; // manager user id
  title: string;
  description: string;
  type: 'refresher' | 'new_lesson';
  source: 'pain_point' | 'incident' | 'manual';
  status: 'pending' | 'approved' | 'rejected';
  createdAt: string;
  suggestedLesson?: Partial<Lesson>; // AI suggestion for admin to review
  approvedLessonId?: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  citations?: Array<{
    documentTitle: string;
    section: string;
    excerpt: string;
  }>;
  createdAt: string;
}

export interface SavedPolicyAnswer {
  id: string;
  question: string;
  answer: string;
  citations?: Array<{
    documentTitle: string;
    section: string;
    excerpt?: string;
  }>;
  savedAt: string;
}

export interface ManagerRecommendation {
  id: string;
  priority: "high" | "medium" | "low";
  title: string;
  description: string;
  actionLabel: string;
  actionHref: string;
}

export interface TeamMemberStatus {
  user: User;
  completionRate: number;
  overdueCount: number;
  streak: number;
  atRisk: boolean;
  gapAreas: string[];
  competencyGaps?: Array<{ domainId: string; domainName: string; masteryPercent: number }>;
  avgMastery?: number;
}

export interface DomainCoverage {
  domainId: string;
  domainName: string;
  staffAssessed: number;
  totalStaff: number;
  avgMastery: number;
  coveragePercent: number;
}

export interface PlatformData {
  organizations: Organization[];
  teams: Team[];
  users: User[];
  lessons: Lesson[];
  assignments: LessonAssignment[];
  progress: LessonProgress[];
  streaks: Streak[];
  userXp: UserXP[];
  incidents: Incident[];
  lessonRequests: LessonRequest[];
  documentChunks: DocumentChunk[];
  uploadedMaterials: UploadedMaterial[];
  competencyDomains: CompetencyDomain[];
  competencyRecords: CompetencyRecord[];
  assessmentEvents: AssessmentEvent[];
  learningSessions: LearningSession[];
  tutorMessages: TutorMessage[];
  domainAssignments: DomainAssignment[];
}