import type { DocumentChunk, Lesson, QuizQuestion } from "@/lib/types";

const STOP_WORDS = new Set([
  "the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for", "of", "is", "are",
  "was", "were", "be", "been", "being", "have", "has", "had", "do", "does", "did", "will",
  "would", "could", "should", "may", "might", "must", "shall", "can", "this", "that",
  "these", "those", "with", "from", "by", "as", "it", "its", "they", "them", "their",
]);

function extractKeywords(text: string): string[] {
  return [
    ...new Set(
      text
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, " ")
        .split(/\s+/)
        .filter((w) => w.length > 3 && !STOP_WORDS.has(w))
    ),
  ].slice(0, 8);
}

function splitIntoChunks(text: string): string[] {
  const cleaned = text.replace(/\s+/g, " ").trim();
  if (!cleaned) return [];

  const sentences = cleaned.split(/(?<=[.!?])\s+(?=[A-Z])/);
  const chunks: string[] = [];
  let current = "";

  for (const sentence of sentences) {
    const trimmed = sentence.trim();
    if (!trimmed) continue;

    if ((current + " " + trimmed).length > 280) {
      if (current) chunks.push(current.trim());
      current = trimmed;
    } else {
      current = current ? `${current} ${trimmed}` : trimmed;
    }
  }
  if (current) chunks.push(current.trim());

  if (chunks.length === 0 && cleaned.length > 0) {
    for (let i = 0; i < cleaned.length; i += 250) {
      chunks.push(cleaned.slice(i, i + 250));
    }
  }

  // Large documents get more bite-sized lessons (max 12)
  const maxChunks = cleaned.length > 50000 ? 24 : cleaned.length > 10000 ? 16 : 8;
  return chunks.slice(0, maxChunks);
}

function titleFromChunk(chunk: string, index: number): string {
  const words = chunk.split(/\s+/).slice(0, 6).join(" ");
  return words.length > 50 ? `Key point ${index + 1}` : words;
}

function buildQuiz(chunk: string, index: number): QuizQuestion[] {
  const words = chunk.split(/\s+/);
  const keyPhrase = words.slice(0, Math.min(12, words.length)).join(" ");

  const distractors = [
    "This procedure is optional and may be skipped when busy",
    "Only senior management needs to follow this rule",
    "Reporting or documentation is not required for this topic",
  ];

  return [
    {
      id: `q-${index}`,
      prompt: "Which statement best reflects this policy section?",
      options: [
        keyPhrase.length > 90 ? keyPhrase.slice(0, 90) + "…" : keyPhrase,
        ...distractors,
      ],
      correctIndex: 0,
      explanation: `Correct — this comes directly from your uploaded material.`,
    },
  ];
}

export interface GeneratedContent {
  lessons: Lesson[];
  chunks: DocumentChunk[];
}

export function generateLessonsFromText(
  orgId: string,
  documentId: string,
  documentTitle: string,
  rawText: string,
  startOrderIndex = 100
): GeneratedContent {
  const textChunks = splitIntoChunks(rawText);
  const lessons: Lesson[] = [];
  const docChunks: DocumentChunk[] = [];

  if (textChunks.length === 0) {
    return { lessons, chunks: docChunks };
  }

  const groupSize = 2;
  for (let i = 0; i < textChunks.length; i += groupSize) {
    const group = textChunks.slice(i, i + groupSize);
    const lessonIndex = Math.floor(i / groupSize);
    const lessonId = `lesson-gen-${documentId}-${lessonIndex}`;

    const slides = group.map((chunk, si) => ({
      id: `slide-${lessonIndex}-${si}`,
      title: titleFromChunk(chunk, si),
      body: chunk,
      durationSeconds: 40,
    }));

    const quizChunk = group[group.length - 1];
    const lesson: Lesson = {
      id: lessonId,
      orgId,
      title: `${documentTitle} — Part ${lessonIndex + 1}`,
      description: `Bite-sized training from ${documentTitle}. ~${Math.max(1, Math.ceil(group.length))} min.`,
      category: "Compliance",
      estimatedMinutes: Math.max(1, Math.min(3, group.length)),
      slides,
      quiz: buildQuiz(quizChunk, lessonIndex),
      sourceDocumentIds: [documentId],
      isAutoGenerated: true,
      xpReward: 15,
      orderIndex: startOrderIndex + lessonIndex,
    };
    lessons.push(lesson);

    group.forEach((chunk, si) => {
      docChunks.push({
        id: `chunk-${documentId}-${lessonIndex}-${si}`,
        orgId,
        documentId,
        documentTitle,
        section: `Part ${lessonIndex + 1}.${si + 1}`,
        content: chunk,
        keywords: extractKeywords(chunk),
      });
    });
  }

  return { lessons, chunks: docChunks };
}