"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

import {
  Building2,
  FileUp,
  BookOpen,
  CheckCircle2,
  Clock,
  Download,
} from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { Organization, UploadedMaterial } from "@/lib/types";
import { downloadAdminFile } from "@/lib/admin/download-file";
interface PlatformSummary {
  organizations: Organization[];
  uploadedMaterials: UploadedMaterial[];
  lessons: Array<{ id: string; orgId: string; title: string; isAutoGenerated?: boolean }>;
  lessonRequests?: any[];
}

export default function AdminDashboardPage() {
  const router = useRouter();
  const [data, setData] = useState<PlatformSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    fetch("/api/admin/platform")
      .then((r) => {
        if (!r.ok) throw new Error("Not authorized — log in again.");
        return r.json();
      })
      .then((json) => {
        setData(json);
        setError(null);
      })
      .catch((e) => setError(e instanceof Error ? e.message : "Failed to load admin data"))
      .finally(() => setLoading(false));
  }, []);

  const resetOrg = async (orgId: string, orgName: string) => {
    if (!confirm(`Reset ${orgName} to ONLY the latest upload? Old lessons and progress will be cleared.`)) return;
    const res = await fetch("/api/admin/reset-training", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ orgId }),
    });
    const result = await res.json();
    alert(result.message ?? result.error);
    window.location.reload();
  };

  const materials = data?.uploadedMaterials ?? [];
  const autoLessons = (data?.lessons ?? []).filter((l) => l.isAutoGenerated);

  const managerSubmissions = materials.filter((m) => !!m.managerRequestNote);

  if (loading) {
    return (
      <div className="mx-auto max-w-5xl px-4 py-24 text-center text-muted-foreground">
        Loading admin dashboard…
      </div>
    );
  }

  if (error) {
    return (
      <div className="mx-auto max-w-5xl px-4 py-24 text-center">
        <p className="text-red-500 mb-4">{error}</p>
        <Button onClick={() => router.push("/admin/login")}>Go to Admin Login</Button>
      </div>
    );
  }

  return (
    <div className="relative z-10 mx-auto max-w-5xl px-4 py-8">
      <div className="mb-8 flex items-center justify-between">
        <div>
          <p className="text-xs uppercase tracking-wider text-amber-400">Private — Founder only</p>
          <h1 className="text-2xl font-bold">CompetencyFlow Admin</h1>
          <p className="text-sm text-muted-foreground">
            Upload client materials for SNF, Behavioral Health, or Home Health → auto-generate bite-sized training on facility-specific topics
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Link
            href="/admin/organizations"
            className={cn(buttonVariants({ variant: "outline" }), "border-slate-600")}
          >
            <Building2 className="h-4 w-4" />
            Organizations
          </Link>
          <Link href="/admin/upload" className={buttonVariants()}>
            <FileUp className="h-4 w-4" />
            Upload files
          </Link>
        </div>
      </div>

      <div className="mb-8 grid gap-4 sm:grid-cols-3">
        <Card
          className="cursor-pointer transition-shadow hover:shadow-md"
          onClick={() => router.push("/admin/organizations")}
        >
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground">Client organizations</CardTitle>
          </CardHeader>
          <CardContent className="text-3xl font-bold">
            {data?.organizations.length ?? "—"}
          </CardContent>
        </Card>
        <Card
          className="cursor-pointer transition-shadow hover:shadow-md"
          onClick={() => router.push("/admin/files")}
        >
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground">Files uploaded</CardTitle>
          </CardHeader>
          <CardContent className="text-3xl font-bold">{materials.length}</CardContent>
        </Card>
        <Card
          className="cursor-pointer transition-shadow hover:shadow-md"
          onClick={() => router.push("/admin/database")}
        >
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground">Auto-generated lessons</CardTitle>
          </CardHeader>
          <CardContent className="text-3xl font-bold">{autoLessons.length}</CardContent>
        </Card>
      </div>

      {/* Pure section for requested lessons from managers (via Submit Materials flow).
          Shows org, manager, downloadable file info + the exact instructions the manager wrote.
          Admin uses this info + regular Upload + AI analyzer to create the lessons. No auto-publish. */}
      <Card className="mb-8 border-blue-200">
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <Clock className="h-4 w-4" />
            Requested Lessons from Managers
          </CardTitle>
          <p className="text-xs text-muted-foreground">
            Submissions via manager "Submit Materials". Download the package (includes file name + instructions). Use the regular Upload page and AI analyzer to create the lessons as requested. Content control stays with Admin.
          </p>
        </CardHeader>
        <CardContent className="space-y-3">
          {(() => {
            const subs =
              managerSubmissions.length > 0
                ? managerSubmissions
                : ((data as any)?.lessonRequests || []).filter(
                    (r: any) => r.status === "pending"
                  );
            const orgsById = new Map((data?.organizations || []).map((o: any) => [o.id, o.name]));
            if (!subs || subs.length === 0) {
              return <p className="text-sm text-muted-foreground">No manager lesson requests yet. Managers submit via their Dashboard → "Submit Materials for New Lessons".</p>;
            }
            // If coming from client materials with notes:
            return (subs as any[]).map((m: any, idx: number) => {
              const isMat = !!m.managerRequestNote;
              const orgName = orgsById.get(m.orgId) || m.orgId || 'Unknown org';
              const mgr = isMat ? (m.managerName || "Manager") : (m.requestedBy || "Manager");
              const fileRef = isMat ? m.fileName : (m.title || 'request');
              const note = isMat ? (m.managerRequestNote || '') : (m.description || '');
              return (
                <div key={idx} className="rounded border p-3 text-sm bg-white">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <div><strong>Organization:</strong> {orgName}</div>
                      <div><strong>Manager:</strong> {mgr}</div>
                      <div><strong>Uploaded file / ref:</strong> {fileRef}</div>
                    </div>
                    <Badge variant="outline" className="text-[10px] self-start">Requested</Badge>
                  </div>
                  <div className="mt-2">
                    <div className="text-xs font-medium">Instructions / request from manager:</div>
                    <div className="mt-0.5 rounded bg-slate-50 p-2 text-xs whitespace-pre-wrap border">{note || "(no details)"}</div>
                  </div>
                  <div className="mt-2 text-[10px] text-muted-foreground">Submitted: {new Date(m.uploadedAt || m.createdAt || Date.now()).toLocaleString()}</div>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {isMat && m.storagePath && (
                      <Button
                        size="sm"
                        onClick={async () => {
                          try {
                            await downloadAdminFile(m.id, m.fileName);
                          } catch (err) {
                            alert(
                              err instanceof Error
                                ? err.message
                                : "Could not download file."
                            );
                          }
                        }}
                        className="gap-1"
                      >
                        <Download className="h-3 w-3" /> Download uploaded file
                      </Button>
                    )}
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => {
                        const content = [
                          "COMPETENCYFLOW — MANAGER LESSON REQUEST PACKAGE",
                          "",
                          `From Organization: ${orgName}`,
                          `Submitted by Manager: ${mgr}`,
                          `File / ref: ${fileRef}`,
                          "",
                          "INSTRUCTIONS THE MANAGER WROTE:",
                          note || "(no additional instructions)",
                          "",
                          "ADMIN NEXT STEPS:",
                          "1. Go to /admin/upload (or org-specific upload).",
                          "2. Upload matching policy/document.",
                          "3. Use the manager instructions above to guide the AI lesson generator / design.",
                          "4. Put resulting lessons in the right categories for the org.",
                        ].join("\n");
                        const blob = new Blob([content], { type: "text/plain" });
                        const url = URL.createObjectURL(blob);
                        const a = document.createElement("a");
                        a.href = url;
                        a.download = `requested-lesson-${String(fileRef || "submission").replace(/\s+/g, "-")}.txt`;
                        a.click();
                        URL.revokeObjectURL(url);
                      }}
                      className="gap-1"
                    >
                      <Download className="h-3 w-3" /> Download instructions summary
                    </Button>
                  </div>
                </div>
              );
            });
          })()}
        </CardContent>
      </Card>

      <div>
        <Card className="bg-white border border-gray-300 shadow-sm">
          <CardHeader className="bg-white">
            <CardTitle className="flex items-center gap-2 text-base text-black font-semibold">
              <Building2 className="h-4 w-4" />
              Organizations (People &amp; Orgs)
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 bg-white">
            {(data?.organizations ?? []).map((org) => (
              <div
                key={org.id}
                className="flex items-center justify-between rounded-lg border border-gray-200 p-3 bg-white text-black hover:bg-gray-50"
              >
                <div>
                  <p className="font-medium text-black">{org.name}</p>
                  <p className="text-xs text-gray-700">{org.industry}</p>
                </div>
                <div className="flex gap-2">
                  <Link
                    href={`/admin/organizations/${org.id}`}
                    className={cn(buttonVariants({ variant: "outline", size: "sm" }))}
                  >
                    View
                  </Link>
                  <Link
                    href={`/admin/upload?org=${org.id}`}
                    className={cn(buttonVariants({ variant: "outline", size: "sm" }))}
                  >
                    Upload
                  </Link>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="text-gray-800 hover:text-black"
                    onClick={() => resetOrg(org.id, org.name)}
                  >
                    Reset to latest
                  </Button>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}