import { NextResponse } from "next/server";
import { readPlatform, writePlatform, assignLessonsToUsers } from "@/lib/server/data-store";
import type { Lesson } from "@/lib/types";

function normalizeDesignedLesson(raw: any, orgId: string, index: number): Lesson {
  const now = Date.now();
  const slides = (raw.slides || []).map((s: any, si: number) => ({
    id: s.id || `slide-${now}-${index}-${si}`,
    title: s.title || "Step",
    body: s.body || "",
    durationSeconds: s.durationSeconds || 45,
  }));

  // Designer returns singular quiz object; normalize to array of 1
  const quizRaw = raw.quiz || {};
  const quiz = [
    {
      id: quizRaw.id || `quiz-${now}-${index}`,
      prompt: quizRaw.prompt || `What is the key point of ${raw.title}?`,
      options: Array.isArray(quizRaw.options) && quizRaw.options.length === 4
        ? quizRaw.options
        : ["Option A", "Option B", "Option C", "Option D"],
      correctIndex: typeof quizRaw.correctIndex === "number" ? quizRaw.correctIndex : 0,
      explanation: quizRaw.explanation || "",
    },
  ];

  return {
    id: raw.id || `lesson-design-${orgId}-${now}-${index}`,
    orgId,
    title: raw.title || "Untitled lesson",
    description: raw.description || "",
    category: raw.category || "General",
    estimatedMinutes: raw.estimatedMinutes || 1,
    slides,
    quiz,
    sourceDocumentIds: raw.sourceDocumentIds || [],
    isAutoGenerated: true,
    xpReward: raw.xpReward || 15,
    orderIndex: raw.orderIndex ?? 100 + index,
    competencyDomainId: raw.competencyDomainId,
  };
}

export async function POST(request: Request) {
  try {
    const { orgId, lessons: proposed, mode = "add" } = await request.json() as {
      orgId?: string;
      lessons?: any[];
      mode?: "add" | "replace";
    };

    if (!orgId || !Array.isArray(proposed) || proposed.length === 0) {
      return NextResponse.json({ error: "orgId and lessons[] required" }, { status: 400 });
    }

    const data = await readPlatform();
    const staffIds = data.users
      .filter((u) => u.orgId === orgId && u.role === "staff")
      .map((u) => u.id);

    // Normalize incoming designer lessons to full Lesson shape
    const normalized = proposed.map((l, i) => normalizeDesignedLesson(l, orgId, i));

    if (mode === "replace") {
      // Remove previous lessons for this org (but keep progress history for records if desired; assignments will be replaced)
      const idsToRemove = new Set(
        data.lessons.filter((l) => l.orgId === orgId).map((l) => l.id)
      );
      data.lessons = data.lessons.filter((l) => !idsToRemove.has(l.id));
      data.assignments = data.assignments.filter((a) => !idsToRemove.has(a.lessonId));
      // We intentionally leave progress entries so old scores aren't lost from stats, but new assignments will drive new progress.
    }

    // Add only new ones (dedup by id)
    const existingIds = new Set(data.lessons.map((l) => l.id));
    const fresh = normalized.filter((l) => !existingIds.has(l.id));
    data.lessons.push(...fresh);

    await writePlatform(data);

    // Auto-assign to all staff in org (uses existing helper which dedupes)
    if (fresh.length > 0 && staffIds.length > 0) {
      await assignLessonsToUsers(
        fresh.map((l) => l.id),
        staffIds
      );
    }

    // Return the applied lessons for client merge
    return NextResponse.json({
      ok: true,
      applied: fresh.length,
      lessons: fresh,
      message: mode === "replace"
        ? "Replaced org lessons with the AI-designed set and reassigned to staff."
        : "Added the AI-designed lessons and assigned to staff.",
    });
  } catch (err: any) {
    console.error("Apply designed lessons error:", err);
    return NextResponse.json({ error: err.message || "Failed to apply designed lessons" }, { status: 500 });
  }
}
