import { callOpenAI } from "@/lib/ai/client";
import {
  buildLessonUserPrompt,
  FOCUSED_LESSON_SYSTEM_PROMPT,
  LESSON_SYSTEM_PROMPT,
} from "@/lib/ai/prompts";
import { prepareDocumentForAI } from "@/lib/ai/document-prep";
import type { GeneratedContent } from "@/lib/lesson-generator";
import type { DocumentChunk, Lesson, QuizQuestion } from "@/lib/types";

interface AILessonSlide {
  title: string;
  body: string;
}

interface AILessonQuiz {
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

interface AILesson {
  title: string;
  description: string;
  category: string;
  estimatedMinutes: number;
  slides: AILessonSlide[];
  quiz: AILessonQuiz;
}

interface AIResponse {
  documentSummary?: string;
  lessons: AILesson[];
}

function extractKeywords(text: string): string[] {
  const STOP = new Set(["the", "and", "for", "that", "with", "this", "from", "are", "was"]);
  return [
    ...new Set(
      text
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, " ")
        .split(/\s+/)
        .filter((w) => w.length > 4 && !STOP.has(w))
    ),
  ].slice(0, 8);
}

function parseAIJson(content: string): AIResponse {
  const trimmed = content.trim();
  const jsonMatch = trimmed.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new Error("AI did not return valid JSON");

  const parsed = JSON.parse(jsonMatch[0]) as AIResponse;
  if (!Array.isArray(parsed.lessons) || parsed.lessons.length === 0) {
    throw new Error("AI returned no lessons");
  }
  return parsed;
}

function validateLesson(raw: AILesson, index: number): AILesson | null {
  if (!raw.title?.trim() || !raw.slides?.length) return null;

  const slides = raw.slides
    .filter((s) => s.title?.trim() && s.body?.trim())
    .slice(0, 3)
    .map((s) => ({
      title: s.title.trim().slice(0, 80),
      body: s.body.trim().slice(0, 520), // allow room for action bullets
    }));

  if (slides.length === 0) return null;

  const options = (raw.quiz?.options ?? []).filter(Boolean).slice(0, 4);
  if (options.length < 4) return null;

  const correctIndex = Math.min(
    Math.max(0, raw.quiz?.correctIndex ?? 0),
    3
  );

  const allowedCats = [
    "Safety", "Compliance", "Clinical", "Operations", "General",
    "Infection Prevention & Control", "Fall Prevention & Post-Fall Management",
    "Abuse, Neglect & Exploitation", "De-escalation & Crisis Intervention",
    "Medication Management", "Documentation & Medical Records",
  ];
  const cat = typeof raw.category === "string" && raw.category.trim()
    ? raw.category.trim()
    : "Compliance";

  return {
    title: raw.title.trim().slice(0, 100),
    description: (raw.description ?? raw.title).trim().slice(0, 220),
    category: allowedCats.some((c) => c.toLowerCase() === cat.toLowerCase()) ? cat : "Compliance",
    estimatedMinutes: [1, 2, 3].includes(raw.estimatedMinutes)
      ? raw.estimatedMinutes
      : 1,
    slides,
    quiz: {
      prompt: raw.quiz.prompt.trim().slice(0, 200),
      options: options.map((o) => o.trim().slice(0, 120)),
      correctIndex,
      explanation: (raw.quiz.explanation ?? "Review the lesson material.").trim().slice(0, 300),
    },
  };
}

function toPlatformLessons(
  aiLessons: AILesson[],
  orgId: string,
  documentId: string,
  documentTitle: string,
  startOrderIndex: number
): GeneratedContent {
  const lessons: Lesson[] = [];
  const chunks: DocumentChunk[] = [];

  aiLessons.forEach((raw, index) => {
    const valid = validateLesson(raw, index);
    if (!valid) return;

    const lessonId = `lesson-ai-${documentId}-${index}`;

    const quiz: QuizQuestion[] = [
      {
        id: `q-${index}`,
        prompt: valid.quiz.prompt,
        options: valid.quiz.options,
        correctIndex: valid.quiz.correctIndex,
        explanation: valid.quiz.explanation,
      },
    ];

    lessons.push({
      id: lessonId,
      orgId,
      title: valid.title,
      description: valid.description,
      category: valid.category,
      estimatedMinutes: valid.estimatedMinutes,
      slides: valid.slides.map((s, si) => ({
        id: `slide-${index}-${si}`,
        title: s.title,
        body: s.body,
        durationSeconds: 40,
      })),
      quiz,
      sourceDocumentIds: [documentId],
      isAutoGenerated: true,
      xpReward: 20,
      orderIndex: startOrderIndex + index,
    });

    valid.slides.forEach((s, si) => {
      chunks.push({
        id: `chunk-ai-${documentId}-${index}-${si}`,
        orgId,
        documentId,
        documentTitle,
        section: `${valid.title} — ${s.title}`,
        content: s.body,
        keywords: extractKeywords(s.body),
      });
    });
  });

  return { lessons, chunks };
}

export async function generateLessonsWithAI(input: {
  orgId: string;
  documentId: string;
  documentTitle: string;
  rawText: string;
  orgName: string;
  industry: string;
  startOrderIndex?: number;
}): Promise<{ content: GeneratedContent; summary: string; usedAI: true }> {
  const preparedText = prepareDocumentForAI(input.rawText);
  const userPrompt = buildLessonUserPrompt({
    documentTitle: input.documentTitle,
    orgName: input.orgName,
    industry: input.industry,
    preparedText,
    charCount: input.rawText.length,
  });

  const content = await callOpenAI({
    system: LESSON_SYSTEM_PROMPT,
    user: userPrompt,
    jsonMode: true,
    temperature: 0.4,
    maxTokens: 4000,
  });

  const parsed = parseAIJson(content);
  const validLessons = parsed.lessons
    .map((l, i) => validateLesson(l, i))
    .filter((l): l is AILesson => l !== null);

  if (validLessons.length === 0) {
    throw new Error("AI lessons failed validation — try uploading again");
  }

  const generated = toPlatformLessons(
    validLessons,
    input.orgId,
    input.documentId,
    input.documentTitle,
    input.startOrderIndex ?? 100
  );

  return {
    content: generated,
    summary: parsed.documentSummary ?? "Training material analyzed and converted to micro-lessons.",
    usedAI: true,
  };
}

export async function generateFocusedLessonWithAI(input: {
  orgId: string;
  documentId: string;
  documentTitle: string;
  rawText: string;
  topic: string;
  startOrderIndex: number;
}): Promise<{ lesson: Lesson; chunks: DocumentChunk[] } | null> {
  const preparedText = prepareDocumentForAI(input.rawText).slice(0, 12000);
  const userPrompt = `Create ONE highly practical, actionable micro-lesson (60-120s) on this topic: "${input.topic}"

DOCUMENT: ${input.documentTitle}

SOURCE MATERIAL (ground EVERYTHING in this only):
---
${preparedText}
---

Follow healthcare trainer rules: action-focused, short bullets/steps for key actions, brief why it matters, scenario Quick Check quiz. 2-3 slides max. estimatedMinutes 1 or 2. Action-oriented title. No invented content.`;



  const content = await callOpenAI({
    system: FOCUSED_LESSON_SYSTEM_PROMPT,
    user: userPrompt,
    jsonMode: true,
    temperature: 0.4,
  });

  const jsonMatch = content.trim().match(/\{[\s\S]*\}/);
  if (!jsonMatch) return null;

  const raw = JSON.parse(jsonMatch[0]) as AILesson;
  const valid = validateLesson(raw, 0);
  if (!valid) return null;

  const generated = toPlatformLessons(
    [valid],
    input.orgId,
    input.documentId,
    input.documentTitle,
    input.startOrderIndex
  );

  const lesson = generated.lessons[0];
  if (!lesson) return null;

  lesson.title = `${input.topic}`.slice(0, 100);
  return { lesson, chunks: generated.chunks };
}