import { buildTeamMemberStatuses } from "@/lib/analytics/team";
import {
  getCategoriesForOrgType,
  getRefresherIntervalDays,
  isRefresherRotationEnabled,
} from "@/lib/competency/domains";
import { buildDomainCoverage } from "@/lib/competency/mastery";
import { buildRefresherCycleSnapshot } from "@/lib/competency/refresher-cycle";
import type { PlatformData } from "@/lib/types";

export interface ManagerIntelligenceContext {
  orgName: string;
  teamName: string;
  managerName: string;
  orgType: string;
  refresherRotationEnabled: boolean;
  teamSummary: string;
  surveyReadiness: string;
  categories: string;
  lessons: string;
  materials: string;
  pendingSubmissions: string;
  staff: string;
  domains: string;
  recentStaffQuestions: string;
  lessonRequests: string;
}

function lessonSourceLabel(
  lesson: {
    sourceDocumentIds: string[];
    isAutoGenerated?: boolean;
    isRefresher?: boolean;
  },
  materials: PlatformData["uploadedMaterials"]
): string {
  if (lesson.isRefresher && lesson.isAutoGenerated) return "auto-rotation refresher";
  if (lesson.isRefresher) return "refresher lesson";
  if (lesson.isAutoGenerated) return "manager-assigned refresher";
  if (lesson.sourceDocumentIds.length === 0) return "admin/seed content";
  const names = lesson.sourceDocumentIds
    .map((id) => materials.find((m) => m.id === id)?.fileName)
    .filter(Boolean);
  return names.length ? `sourced from ${names.join(", ")}` : "from uploaded material";
}

export function buildManagerIntelligenceContext(
  platform: PlatformData,
  orgId: string,
  teamId: string,
  managerId: string
): ManagerIntelligenceContext {
  const org = platform.organizations.find((o) => o.id === orgId);
  const team = platform.teams.find((t) => t.id === teamId);
  const manager = platform.users.find((u) => u.id === managerId);
  const orgType = org?.orgType ?? "snf";
  const rotationOn = isRefresherRotationEnabled(org);

  const staff = platform.users.filter(
    (u) => u.orgId === orgId && u.teamId === teamId && u.role === "staff"
  );
  const staffIds = new Set(staff.map((s) => s.id));

  const orgLessons = platform.lessons.filter((l) => l.orgId === orgId);
  const orgDomains = platform.competencyDomains.filter((d) => d.orgId === orgId);
  const orgMaterials = platform.uploadedMaterials.filter((m) => m.orgId === orgId);

  const teamStatuses = buildTeamMemberStatuses(
    staff,
    platform.assignments,
    platform.progress,
    platform.streaks,
    platform.lessons,
    platform.competencyRecords,
    platform.competencyDomains
  );

  const domainCoverage = buildDomainCoverage(
    staff,
    platform.competencyDomains,
    platform.competencyRecords,
    orgId
  );

  const atRiskCount = teamStatuses.filter((m) => m.atRisk).length;
  const avgCompletion =
    teamStatuses.length > 0
      ? Math.round(
          teamStatuses.reduce((sum, m) => sum + m.completionRate, 0) /
            teamStatuses.length
        )
      : 0;

  const requiredCategories = getCategoriesForOrgType(orgType);
  const surveyLines = requiredCategories.map((cat) => {
    const dom = domainCoverage.find((d) => d.domainName === cat);
    const catLessons = orgLessons.filter((l) => l.category === cat);
    const ready = catLessons.length > 0 && (dom?.avgMastery ?? 0) >= 70;
    return `- ${cat}: ${ready ? "READY" : "GAP"} · ${catLessons.length} lesson(s) · team mastery ${Math.round(dom?.avgMastery ?? 0)}% · ${dom?.staffAssessed ?? 0}/${staff.length} staff assessed`;
  });

  const categoryLines = orgDomains.map((d) => {
    const count = orgLessons.filter((l) => l.category === d.name).length;
    const interval = rotationOn ? `${d.refresherIntervalDays ?? 90}d` : "rotation off";
    return `- ${d.name}: interval ${interval} · ${count} lesson(s)`;
  });

  const lessonLines = orgLessons.map((l) => {
    const assigned = platform.assignments.filter((a) => a.lessonId === l.id).length;
    const completed = platform.progress.filter(
      (p) => p.lessonId === l.id && p.status === "completed"
    ).length;
    const source = lessonSourceLabel(l, orgMaterials);
    return `- ${l.id}: "${l.title}" · ${l.category} · ${l.estimatedMinutes} min · assigned ${assigned} staff · ${completed} completions · ${source}`;
  });

  const readyMaterials = orgMaterials
    .filter((m) => m.status === "ready")
    .map(
      (m) =>
        `- ${m.id}: ${m.fileName} · ${m.lessonIds.length} lessons built · tags: ${(m.assignedCategories ?? []).join(", ") || "n/a"}`
    );

  const pendingSubmissions = orgMaterials
    .filter((m) => m.status === "submitted_by_manager")
    .map(
      (m) =>
        `- ${m.fileName} · waiting on admin · ${m.managerName ?? "manager"}: ${m.managerRequestNote?.slice(0, 140) || "(no note)"}`
    );

  const staffLines = teamStatuses.map((m) => {
    const u = m.user;
    const assignedCount = platform.assignments.filter((a) => a.userId === u.id).length;
    const prio = (u.priorityCategories ?? []).join(", ") || "not set";
    const intervalNotes = rotationOn
      ? (u.priorityCategories ?? [])
          .map(
            (cat) =>
              `${cat}=${getRefresherIntervalDays(cat, {
                user: u,
                domains: orgDomains,
                orgId,
              })}d`
          )
          .join("; ") || "n/a"
      : "n/a (rotation off)";

    let rotationNote = "rotation disabled for this org";
    if (rotationOn) {
      const snap = buildRefresherCycleSnapshot(
        u,
        orgDomains,
        platform.lessons,
        platform.progress
      );
      if (snap?.currentDue) {
        rotationNote = `due now: ${snap.currentDue.category}`;
      } else if (snap?.nextUp) {
        rotationNote = `next up: ${snap.nextUp.category} (~${snap.nextUp.daysUntilDue}d)`;
      } else if (snap) {
        rotationNote = "caught up on rotation";
      } else {
        rotationNote = "no priority categories for rotation";
      }
    }

    const gaps =
      [
        ...m.gapAreas.map((g) => `lesson: ${g}`),
        ...(m.competencyGaps ?? []).map(
          (g) => `competency: ${g.domainName} (${g.masteryPercent}%)`
        ),
      ].join("; ") || "none";

    return `- ${u.id}: ${u.name}${u.jobTitle ? ` (${u.jobTitle})` : ""} · ${m.completionRate}% lessons done · ${m.avgMastery}% mastery · ${assignedCount} assigned · streak ${m.streak}${m.overdueCount ? ` · ${m.overdueCount} overdue` : ""}${m.atRisk ? " [AT RISK]" : ""}
  priorities: ${prio}
  intervals: ${intervalNotes}
  rotation: ${rotationNote}
  gaps: ${gaps}`;
  });

  const domainLines = domainCoverage.map(
    (d) =>
      `- ${d.domainId}: ${d.domainName} · avg ${d.avgMastery}% · ${d.staffAssessed}/${staff.length} assessed`
  );

  const recentQuestions = platform.tutorMessages
    .filter((m) => staffIds.has(m.userId) && m.role === "user")
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 12)
    .map((m) => {
      const name = staff.find((s) => s.id === m.userId)?.name ?? m.userId;
      return `- ${name}: "${m.content.slice(0, 120)}${m.content.length > 120 ? "…" : ""}"`;
    });

  const requestLines = (platform.lessonRequests ?? [])
    .filter((r) => r.orgId === orgId)
    .slice(-8)
    .map(
      (r) =>
        `- ${r.title} (${r.type}) · ${r.status} · ${r.description?.slice(0, 80) ?? ""}`
    );

  return {
    orgName: org?.name ?? "Organization",
    teamName: team?.name ?? "Team",
    managerName: manager?.name ?? "Manager",
    orgType,
    refresherRotationEnabled: rotationOn,
    teamSummary: `${staff.length} staff · ${avgCompletion}% avg completion · ${atRiskCount} at risk · ${orgLessons.length} lessons in library · refresher rotation ${rotationOn ? "ON" : "OFF"}`,
    surveyReadiness: surveyLines.join("\n"),
    categories: categoryLines.join("\n") || "(no categories)",
    lessons: lessonLines.join("\n") || "(no lessons)",
    materials: readyMaterials.join("\n") || "(no processed uploads)",
    pendingSubmissions: pendingSubmissions.join("\n") || "(none)",
    staff: staffLines.join("\n") || "(no staff on team)",
    domains: domainLines.join("\n") || "(no domain data)",
    recentStaffQuestions:
      recentQuestions.join("\n") ||
      "(no logged staff questions yet — staff Ask Policy chats may be session-only)",
    lessonRequests: requestLines.join("\n") || "(none)",
  };
}