import { NextResponse } from "next/server";
import { generateRefresherLesson } from "@/lib/incidents/generate-lesson";
import {
  addLessonAndAssign,
  assignLessonsToUsers,
  readPlatform,
  updateUser,
} from "@/lib/server/data-store";
import type { Incident, Lesson, User } from "@/lib/types";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      orgId,
      teamId,
      managerId,
      mode,
      lessonId,
      userIds,
      customLesson,
      incidentText,
      categoryIntervalDays,
      category,
    } = body as {
      orgId?: string;
      teamId?: string;
      managerId?: string;
      mode?: "existing" | "custom";
      lessonId?: string;
      userIds?: string[];
      customLesson?: {
        title: string;
        keyPoints?: string;
        category: string;
      };
      incidentText?: string;
      categoryIntervalDays?: number;
      category?: string;
    };

    if (!orgId || !managerId || !userIds?.length) {
      return NextResponse.json(
        { error: "orgId, managerId, and userIds are required" },
        { status: 400 }
      );
    }

    const platform = await readPlatform();
    const manager = platform.users.find((u) => u.id === managerId);
    if (!manager || manager.role !== "manager" || manager.orgId !== orgId) {
      return NextResponse.json({ error: "Invalid manager" }, { status: 403 });
    }

    const validUserIds = userIds.filter((id) => {
      const u = platform.users.find((x) => x.id === id);
      return (
        u &&
        u.orgId === orgId &&
        u.role === "staff" &&
        (!teamId || u.teamId === teamId)
      );
    });

    if (validUserIds.length === 0) {
      return NextResponse.json({ error: "No valid staff selected" }, { status: 400 });
    }

    const updatedUsers: User[] = [];
    const intervalCategory = category ?? customLesson?.category;
    if (intervalCategory && categoryIntervalDays) {
      for (const uid of validUserIds) {
        const u = platform.users.find((x) => x.id === uid);
        if (!u) continue;
        const intervals = { ...(u.refresherIntervals || {}) };
        intervals[intervalCategory] = categoryIntervalDays;
        const updated = await updateUser(uid, { refresherIntervals: intervals });
        if (updated) updatedUsers.push(updated);
      }
    }

    let lesson: Lesson | undefined;
    let newAssignments: Array<{
      id: string;
      lessonId: string;
      userId: string;
      assignedAt: string;
      dueAt?: string;
    }> = [];

    if (mode === "existing" && lessonId) {
      const existing = platform.lessons.find(
        (l) => l.id === lessonId && l.orgId === orgId
      );
      if (!existing) {
        return NextResponse.json({ error: "Lesson not found" }, { status: 404 });
      }

      await assignLessonsToUsers([lessonId], validUserIds);
      const fresh = await readPlatform();
      lesson = existing;
      newAssignments = fresh.assignments.filter(
        (a) => a.lessonId === lessonId && validUserIds.includes(a.userId)
      );
    } else if (mode === "custom" && customLesson?.title && customLesson.category) {
      const incident: Incident = {
        id: `inc-${Date.now()}`,
        orgId,
        teamId: teamId ?? manager.teamId,
        reportedBy: managerId,
        title: customLesson.title,
        description: customLesson.keyPoints || incidentText || customLesson.title,
        severity: "medium",
        category: customLesson.category,
        occurredAt: new Date().toISOString(),
        status: "open",
      };

      const generated = generateRefresherLesson(incident, platform.documentChunks);
      const refresherLesson: Lesson = {
        ...generated,
        id: `lesson-refresher-${Date.now()}`,
        title: customLesson.title.trim(),
        description:
          customLesson.keyPoints?.trim() ||
          `Targeted refresher on ${customLesson.category}`,
        isAutoGenerated: true,
        isRefresher: true,
      };

      const dueAt = new Date();
      dueAt.setDate(dueAt.getDate() + 3);
      const result = await addLessonAndAssign(refresherLesson, validUserIds, {
        dueAt: dueAt.toISOString().split("T")[0],
      });
      lesson = result.lesson;
      newAssignments = result.assignments;
    } else {
      return NextResponse.json(
        { error: "Invalid assignment mode or missing fields" },
        { status: 400 }
      );
    }

    return NextResponse.json({
      ok: true,
      lesson,
      assignments: newAssignments,
      users: updatedUsers,
      assignedCount: validUserIds.length,
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Assignment failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}